<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://bmstu.ru/logsearch"
                  xmlns:xs="http://www.w3.org/2001/XMLSchema"
                  targetNamespace="http://bmstu.ru/logsearch">
    <wsdl:types>
        <xs:schema>
            <xs:import schemaLocation="../xsd/LogSearcherSchema.xsd" namespace="http://bmstu.ru/logsearch"/>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="SearchInfo">
        <wsdl:part name="parameter" element="tns:SearchInfo"/>
    </wsdl:message>

    <wsdl:message name="SearchInfoResult">
        <wsdl:part name="parameter" element="tns:SearchInfoResult"/>
    </wsdl:message>

    <wsdl:portType name="LogSearchService">
        <wsdl:operation name="LogSearch">
            <wsdl:input message="tns:SearchInfo"/>
            <wsdl:output message="tns:SearchInfoResult"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="LogSearcherPortSoap11" type="tns:LogSearchService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="LogSearch">
            <soap:operation soapAction="logSearch" style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="LogSearcherPortService">
        <wsdl:port binding="tns:LogSearcherPortSoap11" name="LogSearcherPortSoap11">
            <soap:address location="http://localhost:8080/ws/LogSearcher.wsdl"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>